/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_salatTimeDialog (void);
GtkWidget* create_mainWindow (void);
GtkWidget* create_prefsWindow (void);
GtkWidget* create_aboutWindow (void);
