/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_salatTimeDialog (void)
{
  GtkWidget *salatTimeDialog;
  GtkWidget *dialog_vbox2;
  GtkWidget *salatNotificationLabel;
  GtkWidget *dialog_action_area2;
  GtkWidget *okbutton2;

  salatTimeDialog = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (salatTimeDialog), _("Namaz Time"));
  gtk_window_set_type_hint (GTK_WINDOW (salatTimeDialog), GDK_WINDOW_TYPE_HINT_DIALOG);

  dialog_vbox2 = GTK_DIALOG (salatTimeDialog)->vbox;
  gtk_widget_show (dialog_vbox2);

  salatNotificationLabel = gtk_label_new (_("It is now the time for salat."));
  gtk_widget_show (salatNotificationLabel);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), salatNotificationLabel, FALSE, FALSE, 0);

  dialog_action_area2 = GTK_DIALOG (salatTimeDialog)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  okbutton2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (salatTimeDialog), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (salatTimeDialog, salatTimeDialog, "salatTimeDialog");
  GLADE_HOOKUP_OBJECT_NO_REF (salatTimeDialog, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (salatTimeDialog, salatNotificationLabel, "salatNotificationLabel");
  GLADE_HOOKUP_OBJECT_NO_REF (salatTimeDialog, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (salatTimeDialog, okbutton2, "okbutton2");

  return salatTimeDialog;
}

GtkWidget*
create_mainWindow (void)
{
  GtkWidget *mainWindow;
  GtkWidget *fixed5;
  GtkWidget *hseparator6;
  GtkWidget *hseparator7;
  GtkWidget *image6;
  GtkWidget *zuhrLabel;
  GtkWidget *asrLabel;
  GtkWidget *maghribLabel;
  GtkWidget *ishaLabel;
  GtkWidget *nextSalatLabel;
  GtkWidget *image1;
  GtkWidget *image4;
  GtkWidget *shuruqLabel;
  GtkWidget *fajrLabel;

  mainWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mainWindow), _("NamazTime"));
  gtk_window_set_position (GTK_WINDOW (mainWindow), GTK_WIN_POS_CENTER);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (mainWindow), TRUE);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (mainWindow), fixed5);

  hseparator6 = gtk_hseparator_new ();
  gtk_widget_show (hseparator6);
  gtk_fixed_put (GTK_FIXED (fixed5), hseparator6, 0, 24);
  gtk_widget_set_size_request (hseparator6, 272, 16);

  hseparator7 = gtk_hseparator_new ();
  gtk_widget_show (hseparator7);
  gtk_fixed_put (GTK_FIXED (fixed5), hseparator7, 0, 136);
  gtk_widget_set_size_request (hseparator7, 272, 16);

  image6 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_fixed_put (GTK_FIXED (fixed5), image6, 8, 144);
  gtk_widget_set_size_request (image6, 21, 34);

  zuhrLabel = gtk_label_new (_("label"));
  gtk_widget_show (zuhrLabel);
  gtk_fixed_put (GTK_FIXED (fixed5), zuhrLabel, 136, 72);
  gtk_widget_set_size_request (zuhrLabel, 128, 16);
  gtk_label_set_ellipsize (GTK_LABEL (zuhrLabel), PANGO_ELLIPSIZE_START);

  asrLabel = gtk_label_new (_("label"));
  gtk_widget_show (asrLabel);
  gtk_fixed_put (GTK_FIXED (fixed5), asrLabel, 136, 88);
  gtk_widget_set_size_request (asrLabel, 128, 16);
  gtk_label_set_ellipsize (GTK_LABEL (asrLabel), PANGO_ELLIPSIZE_START);

  maghribLabel = gtk_label_new (_("label"));
  gtk_widget_show (maghribLabel);
  gtk_fixed_put (GTK_FIXED (fixed5), maghribLabel, 136, 104);
  gtk_widget_set_size_request (maghribLabel, 128, 16);
  gtk_label_set_ellipsize (GTK_LABEL (maghribLabel), PANGO_ELLIPSIZE_START);

  ishaLabel = gtk_label_new (_("label"));
  gtk_widget_show (ishaLabel);
  gtk_fixed_put (GTK_FIXED (fixed5), ishaLabel, 136, 120);
  gtk_widget_set_size_request (ishaLabel, 128, 16);
  gtk_label_set_ellipsize (GTK_LABEL (ishaLabel), PANGO_ELLIPSIZE_START);

  nextSalatLabel = gtk_label_new (_("label43"));
  gtk_widget_show (nextSalatLabel);
  gtk_fixed_put (GTK_FIXED (fixed5), nextSalatLabel, 32, 148);
  gtk_widget_set_size_request (nextSalatLabel, 240, 28);
  gtk_label_set_ellipsize (GTK_LABEL (nextSalatLabel), PANGO_ELLIPSIZE_START);

  image1 = create_pixmap (mainWindow, NULL);
  gtk_widget_show (image1);
  gtk_fixed_put (GTK_FIXED (fixed5), image1, 8, 40);
  gtk_widget_set_size_request (image1, 120, 96);

  image4 = create_pixmap (mainWindow, "mainWindow.png");
  gtk_widget_show (image4);
  gtk_fixed_put (GTK_FIXED (fixed5), image4, 0, 0);
  gtk_widget_set_size_request (image4, 272, 32);

  shuruqLabel = gtk_label_new (_("label"));
  gtk_widget_show (shuruqLabel);
  gtk_fixed_put (GTK_FIXED (fixed5), shuruqLabel, 136, 56);
  gtk_widget_set_size_request (shuruqLabel, 128, 16);
  gtk_label_set_ellipsize (GTK_LABEL (shuruqLabel), PANGO_ELLIPSIZE_START);

  fajrLabel = gtk_label_new (_("label"));
  gtk_widget_show (fajrLabel);
  gtk_fixed_put (GTK_FIXED (fixed5), fajrLabel, 136, 40);
  gtk_widget_set_size_request (fajrLabel, 128, 16);
  gtk_label_set_ellipsize (GTK_LABEL (fajrLabel), PANGO_ELLIPSIZE_START);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainWindow, mainWindow, "mainWindow");
  GLADE_HOOKUP_OBJECT (mainWindow, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (mainWindow, hseparator6, "hseparator6");
  GLADE_HOOKUP_OBJECT (mainWindow, hseparator7, "hseparator7");
  GLADE_HOOKUP_OBJECT (mainWindow, image6, "image6");
  GLADE_HOOKUP_OBJECT (mainWindow, zuhrLabel, "zuhrLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, asrLabel, "asrLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, maghribLabel, "maghribLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, ishaLabel, "ishaLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, nextSalatLabel, "nextSalatLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, image1, "image1");
  GLADE_HOOKUP_OBJECT (mainWindow, image4, "image4");
  GLADE_HOOKUP_OBJECT (mainWindow, shuruqLabel, "shuruqLabel");
  GLADE_HOOKUP_OBJECT (mainWindow, fajrLabel, "fajrLabel");

  return mainWindow;
}

GtkWidget*
create_prefsWindow (void)
{
  GtkWidget *prefsWindow;
  GtkWidget *fixed1;
  GtkWidget *frame9;
  GtkWidget *frame12;
  GtkWidget *fixed7;
  GtkWidget *lat_entry;
  GtkWidget *gmtdiff_entry;
  GtkWidget *locName_entry;
  GtkWidget *long_entry;
  GtkWidget *label43;
  GtkWidget *label44;
  GtkWidget *vseparator4;
  GtkWidget *label46;
  GtkWidget *sealevel_entry;
  GtkWidget *label45;
  GtkWidget *hseparator10;
  GtkWidget *label47;
  GtkWidget *label48;
  GtkWidget *dst_checkbox;
  GtkWidget *label40;
  GtkWidget *image3;
  GtkWidget *hseparator3;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;
  GtkWidget *image2;
  GtkWidget *label23;
  GtkWidget *hseparator2;
  GtkWidget *frame10;
  GtkWidget *alignment10;
  GtkWidget *fixed3;
  GtkWidget *mathhab;
  GtkWidget *label35;
  GtkWidget *frame11;
  GtkWidget *alignment11;
  GtkWidget *fixed4;
  GtkWidget *reminderOptionBox;
  GtkWidget *label36;

  prefsWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (prefsWindow), _("NamazTime"));
  gtk_window_set_position (GTK_WINDOW (prefsWindow), GTK_WIN_POS_CENTER);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (prefsWindow), fixed1);

  frame9 = gtk_frame_new (NULL);
  gtk_widget_show (frame9);
  gtk_fixed_put (GTK_FIXED (fixed1), frame9, 8, 40);
  gtk_widget_set_size_request (frame9, 424, 160);
  gtk_frame_set_shadow_type (GTK_FRAME (frame9), GTK_SHADOW_NONE);

  frame12 = gtk_frame_new (NULL);
  gtk_widget_show (frame12);
  gtk_container_add (GTK_CONTAINER (frame9), frame12);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (frame12), fixed7);

  lat_entry = gtk_entry_new ();
  gtk_widget_show (lat_entry);
  gtk_fixed_put (GTK_FIXED (fixed7), lat_entry, 104, 32);
  gtk_widget_set_size_request (lat_entry, 104, 24);

  gmtdiff_entry = gtk_entry_new ();
  gtk_widget_show (gmtdiff_entry);
  gtk_fixed_put (GTK_FIXED (fixed7), gmtdiff_entry, 104, 64);
  gtk_widget_set_size_request (gmtdiff_entry, 160, 24);

  locName_entry = gtk_entry_new ();
  gtk_widget_show (locName_entry);
  gtk_fixed_put (GTK_FIXED (fixed7), locName_entry, 104, 0);
  gtk_widget_set_size_request (locName_entry, 144, 27);

  long_entry = gtk_entry_new ();
  gtk_widget_show (long_entry);
  gtk_fixed_put (GTK_FIXED (fixed7), long_entry, 288, 32);
  gtk_widget_set_size_request (long_entry, 112, 24);

  label43 = gtk_label_new (_("<span size=\"small\">Location Name: </span>"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed7), label43, 8, 8);
  gtk_widget_set_size_request (label43, 88, 16);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  label44 = gtk_label_new (_("<span size=\"small\">Latitude: </span>"));
  gtk_widget_show (label44);
  gtk_fixed_put (GTK_FIXED (fixed7), label44, 8, 40);
  gtk_widget_set_size_request (label44, 56, 16);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);

  vseparator4 = gtk_vseparator_new ();
  gtk_widget_show (vseparator4);
  gtk_fixed_put (GTK_FIXED (fixed7), vseparator4, 208, 32);
  gtk_widget_set_size_request (vseparator4, 16, 24);

  label46 = gtk_label_new (_("<span size=\"small\">Longitude: </span>"));
  gtk_widget_show (label46);
  gtk_fixed_put (GTK_FIXED (fixed7), label46, 224, 40);
  gtk_widget_set_size_request (label46, 64, 16);
  gtk_label_set_use_markup (GTK_LABEL (label46), TRUE);

  sealevel_entry = gtk_entry_new ();
  gtk_widget_show (sealevel_entry);
  gtk_fixed_put (GTK_FIXED (fixed7), sealevel_entry, 136, 104);
  gtk_widget_set_size_request (sealevel_entry, 152, 27);

  label45 = gtk_label_new (_("<span size=\"small\">GMT Difference: </span>"));
  gtk_widget_show (label45);
  gtk_fixed_put (GTK_FIXED (fixed7), label45, 8, 72);
  gtk_widget_set_size_request (label45, 96, 16);
  gtk_label_set_use_markup (GTK_LABEL (label45), TRUE);

  hseparator10 = gtk_hseparator_new ();
  gtk_widget_show (hseparator10);
  gtk_fixed_put (GTK_FIXED (fixed7), hseparator10, 8, 88);
  gtk_widget_set_size_request (hseparator10, 400, 16);

  label47 = gtk_label_new (_("<span size=\"small\">Sea Level (Optional): </span>"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed7), label47, 8, 112);
  gtk_widget_set_size_request (label47, 128, 16);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  label48 = gtk_label_new (_("<span size=\"small\">Default: 0</span>"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed7), label48, 304, 112);
  gtk_widget_set_size_request (label48, 56, 16);
  gtk_label_set_use_markup (GTK_LABEL (label48), TRUE);

  dst_checkbox = gtk_check_button_new_with_mnemonic (_("DST"));
  gtk_widget_show (dst_checkbox);
  gtk_fixed_put (GTK_FIXED (fixed7), dst_checkbox, 264, 64);
  gtk_widget_set_size_request (dst_checkbox, 64, 24);

  label40 = gtk_label_new (_("<span size=\"small\"><b>Location Setup</b></span>"));
  gtk_widget_show (label40);
  gtk_frame_set_label_widget (GTK_FRAME (frame12), label40);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  image3 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_fixed_put (GTK_FIXED (fixed1), image3, 24, 320);
  gtk_widget_set_size_request (image3, 21, 21);

  hseparator3 = gtk_hseparator_new ();
  gtk_widget_show (hseparator3);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator3, 0, 352);
  gtk_widget_set_size_request (hseparator3, 440, 16);

  dialog_action_area1 = gtk_hbutton_box_new ();
  gtk_widget_show (dialog_action_area1);
  gtk_fixed_put (GTK_FIXED (fixed1), dialog_action_area1, 0, 360);
  gtk_widget_set_size_request (dialog_action_area1, 432, 43);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);
  gtk_box_set_spacing (GTK_BOX (dialog_action_area1), 5);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_container_add (GTK_CONTAINER (dialog_action_area1), cancelbutton1);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_container_add (GTK_CONTAINER (dialog_action_area1), okbutton1);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  image2 = create_pixmap (prefsWindow, "preferences.png");
  gtk_widget_show (image2);
  gtk_fixed_put (GTK_FIXED (fixed1), image2, 0, 0);
  gtk_widget_set_size_request (image2, 440, 32);

  label23 = gtk_label_new (_("<span size=\"small\"><b>You can obtain your city's latitude and longitude information from:</b> http://www.heavens-above.com/countries.asp</span>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed1), label23, 48, 320);
  gtk_widget_set_size_request (label23, 384, 32);
  GTK_WIDGET_SET_FLAGS (label23, GTK_CAN_FOCUS);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label23), TRUE);
  gtk_label_set_selectable (GTK_LABEL (label23), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label23), 0.37, 0);

  hseparator2 = gtk_hseparator_new ();
  gtk_widget_show (hseparator2);
  gtk_fixed_put (GTK_FIXED (fixed1), hseparator2, 0, 24);
  gtk_widget_set_size_request (hseparator2, 440, 16);

  frame10 = gtk_frame_new (NULL);
  gtk_widget_show (frame10);
  gtk_fixed_put (GTK_FIXED (fixed1), frame10, 8, 208);
  gtk_widget_set_size_request (frame10, 424, 49);

  alignment10 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (frame10), alignment10);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment10), 0, 0, 12, 0);

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (alignment10), fixed3);

  mathhab = gtk_combo_box_entry_new_text ();
  gtk_widget_show (mathhab);
  gtk_fixed_put (GTK_FIXED (fixed3), mathhab, 0, 4);
  gtk_widget_set_size_request (mathhab, 360, 28);
  gtk_combo_box_append_text (GTK_COMBO_BOX (mathhab), _("Default"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mathhab), _("Egyptian General Authority of Survey"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mathhab), _("University of Islamic Sciences, Karachi (Shaf'i)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mathhab), _("University of Islamic Sciences, Karachi (Hanafi)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mathhab), _("Islamic Society of North America"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mathhab), _("Muslim World League (MWL)"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mathhab), _("Umm Al-Qurra, Saudi Arabia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (mathhab), _("Fixed Ishaa Interval (always 90)"));

  label35 = gtk_label_new (_("<span size=\"small\"><b>Calculation Settings</b></span>"));
  gtk_widget_show (label35);
  gtk_frame_set_label_widget (GTK_FRAME (frame10), label35);
  gtk_label_set_use_markup (GTK_LABEL (label35), TRUE);

  frame11 = gtk_frame_new (NULL);
  gtk_widget_show (frame11);
  gtk_fixed_put (GTK_FIXED (fixed1), frame11, 8, 264);
  gtk_widget_set_size_request (frame11, 424, 47);

  alignment11 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (frame11), alignment11);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment11), 0, 0, 12, 0);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (alignment11), fixed4);

  reminderOptionBox = gtk_check_button_new_with_mnemonic (_("Show a reminder dialog box at the time of the prayer."));
  gtk_widget_show (reminderOptionBox);
  gtk_fixed_put (GTK_FIXED (fixed4), reminderOptionBox, 0, 6);
  gtk_widget_set_size_request (reminderOptionBox, 376, 18);

  label36 = gtk_label_new (_("<span size=\"small\"><b>Notification Settings</b></span>"));
  gtk_widget_show (label36);
  gtk_frame_set_label_widget (GTK_FRAME (frame11), label36);
  gtk_label_set_use_markup (GTK_LABEL (label36), TRUE);

  g_signal_connect ((gpointer) cancelbutton1, "clicked",
                    G_CALLBACK (on_cancelbutton1_clicked),
                    NULL);
  g_signal_connect ((gpointer) okbutton1, "clicked",
                    G_CALLBACK (on_okbutton1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (prefsWindow, prefsWindow, "prefsWindow");
  GLADE_HOOKUP_OBJECT (prefsWindow, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (prefsWindow, frame9, "frame9");
  GLADE_HOOKUP_OBJECT (prefsWindow, frame12, "frame12");
  GLADE_HOOKUP_OBJECT (prefsWindow, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (prefsWindow, lat_entry, "lat_entry");
  GLADE_HOOKUP_OBJECT (prefsWindow, gmtdiff_entry, "gmtdiff_entry");
  GLADE_HOOKUP_OBJECT (prefsWindow, locName_entry, "locName_entry");
  GLADE_HOOKUP_OBJECT (prefsWindow, long_entry, "long_entry");
  GLADE_HOOKUP_OBJECT (prefsWindow, label43, "label43");
  GLADE_HOOKUP_OBJECT (prefsWindow, label44, "label44");
  GLADE_HOOKUP_OBJECT (prefsWindow, vseparator4, "vseparator4");
  GLADE_HOOKUP_OBJECT (prefsWindow, label46, "label46");
  GLADE_HOOKUP_OBJECT (prefsWindow, sealevel_entry, "sealevel_entry");
  GLADE_HOOKUP_OBJECT (prefsWindow, label45, "label45");
  GLADE_HOOKUP_OBJECT (prefsWindow, hseparator10, "hseparator10");
  GLADE_HOOKUP_OBJECT (prefsWindow, label47, "label47");
  GLADE_HOOKUP_OBJECT (prefsWindow, label48, "label48");
  GLADE_HOOKUP_OBJECT (prefsWindow, dst_checkbox, "dst_checkbox");
  GLADE_HOOKUP_OBJECT (prefsWindow, label40, "label40");
  GLADE_HOOKUP_OBJECT (prefsWindow, image3, "image3");
  GLADE_HOOKUP_OBJECT (prefsWindow, hseparator3, "hseparator3");
  GLADE_HOOKUP_OBJECT (prefsWindow, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (prefsWindow, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (prefsWindow, okbutton1, "okbutton1");
  GLADE_HOOKUP_OBJECT (prefsWindow, image2, "image2");
  GLADE_HOOKUP_OBJECT (prefsWindow, label23, "label23");
  GLADE_HOOKUP_OBJECT (prefsWindow, hseparator2, "hseparator2");
  GLADE_HOOKUP_OBJECT (prefsWindow, frame10, "frame10");
  GLADE_HOOKUP_OBJECT (prefsWindow, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (prefsWindow, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (prefsWindow, mathhab, "mathhab");
  GLADE_HOOKUP_OBJECT (prefsWindow, label35, "label35");
  GLADE_HOOKUP_OBJECT (prefsWindow, frame11, "frame11");
  GLADE_HOOKUP_OBJECT (prefsWindow, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (prefsWindow, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (prefsWindow, reminderOptionBox, "reminderOptionBox");
  GLADE_HOOKUP_OBJECT (prefsWindow, label36, "label36");

  gtk_widget_grab_default (okbutton1);
  return prefsWindow;
}

GtkWidget*
create_aboutWindow (void)
{
  GtkWidget *aboutWindow;
  GtkWidget *fixed6;
  GtkWidget *hseparator8;
  GtkWidget *hseparator9;
  GtkWidget *image7;
  GtkWidget *label38;
  GtkWidget *label37;

  aboutWindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (aboutWindow), _("About"));

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (aboutWindow), fixed6);

  hseparator8 = gtk_hseparator_new ();
  gtk_widget_show (hseparator8);
  gtk_fixed_put (GTK_FIXED (fixed6), hseparator8, 0, 24);
  gtk_widget_set_size_request (hseparator8, 328, 16);

  hseparator9 = gtk_hseparator_new ();
  gtk_widget_show (hseparator9);
  gtk_fixed_put (GTK_FIXED (fixed6), hseparator9, 0, 224);
  gtk_widget_set_size_request (hseparator9, 328, 16);

  image7 = create_pixmap (aboutWindow, "aboutWindow.png");
  gtk_widget_show (image7);
  gtk_fixed_put (GTK_FIXED (fixed6), image7, 0, 0);
  gtk_widget_set_size_request (image7, 328, 32);

  label38 = gtk_label_new (_("<span size=\"small\"><b>About NamazTime v1.0</b></span>"));
  gtk_widget_show (label38);
  gtk_fixed_put (GTK_FIXED (fixed6), label38, 8, 48);
  gtk_widget_set_size_request (label38, 152, 16);
  gtk_label_set_use_markup (GTK_LABEL (label38), TRUE);

  label37 = gtk_label_new (_("<span size=\"small\">NamazTime is based on the ITL Prayer Times library written by Thamer Mahmoud.  More information can be found at http://www.arabeyes.org.  \n\nGraphcis by Soner Eker (sonereker@gmail.com)\n\nFor updates on this actual application, please visit \nhttp://whatstheplot.com/blog.</span>"));
  gtk_widget_show (label37);
  gtk_fixed_put (GTK_FIXED (fixed6), label37, 8, 64);
  gtk_widget_set_size_request (label37, 320, 162);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);
  gtk_label_set_line_wrap (GTK_LABEL (label37), TRUE);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutWindow, aboutWindow, "aboutWindow");
  GLADE_HOOKUP_OBJECT (aboutWindow, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (aboutWindow, hseparator8, "hseparator8");
  GLADE_HOOKUP_OBJECT (aboutWindow, hseparator9, "hseparator9");
  GLADE_HOOKUP_OBJECT (aboutWindow, image7, "image7");
  GLADE_HOOKUP_OBJECT (aboutWindow, label38, "label38");
  GLADE_HOOKUP_OBJECT (aboutWindow, label37, "label37");

  return aboutWindow;
}

