.TH minbar 1 2007-05-17 minbar "minbar"
.SH NAME
Minbar - Gnome Prayer Times
.SH SYNOPSIS
.B
.I minbar
[OPTIONS]
.SH DESCRIPTION
.I minbar
is a Gnome Islamic prayer times application. At first start, you have to configure it with your location, time zone and madhab details. 
\.
.SH OPTIONS
Help options
.TP
\fB\-?\fR, \fB\-\-help\fR
Show help options
.PP
Application options
.TP
\fB\-h\fR, \fB\-\-hide\fR
Hide main window on start up, minbar will stay in notification area.
.SH AUTHORS
- Djihed Afifi (djihed@gmail.com) - http://djihed.com/minbar
